name: "[CI] Flask Release"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - homolog
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker HUB
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            jvictorsm/jvictorsm:${{ needs.build.outputs.NEW_VERSION }} 
            jvictorsm/jvictorsm:${{ needs.build.outputs.TAG }} 